version: "2.3"
services:
  jupyter:
    image: sidazhou/scipy-notebook:latest
    container_name: "jupyter"
    network_mode: "bridge"
    ports:
      - "8836:8888"
    # networks:
    #   - sdbridge
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb
      # - neo4j:neo4j
    volumes:
      - /home/sidz:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - NB_UID=1011
      - NB_GID=1011
    user: root
    # cpus: "30"
    # mem_limit: "400G"

    # core dumps
    # https://github.com/moby/moby/issues/11740
    ulimits:
      core: -1

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    network_mode: "bridge"
    ports:
      - "8850:27017"
    volumes:
      - /home/sidz/mongodb:/data/db

  hyperopt-mongo-worker:
    image: sidazhou/scipy-notebook:latest
    container_name: "hyperopt-mongo-worker"
    network_mode: "bridge"
    depends_on:
      - jupyter
      - mongodb
    links:
      - mongodb:mongodb
    command: ["hyperopt-mongo-worker", "--mongo=mongodb:27017/hyperopt_db", "--poll-interval=0.1"]
    # volumes:
    #   - ./hyperopt-mongo-worker/:/hyperopt/
#   neo4j:
#     image: neo4j:latest
#     ports:
#       - "7474:7474"
#       - "7473:7473"
#       - "7687:7687"
#     volumes:
#       - $HOME/Documents/hengchang/neo4j/data:/data
#       - $HOME/Documents/hengchang/neo4j/logs:/logs
#       - $HOME/Documents/hengchang/neo4j/import:/var/lib/neo4j/import
#       - $HOME/Documents/hengchang/neo4j/conf/:/conf/
# networks:
#   sdbridge:

# docker-compose down
# docker rm $(docker ps -q -f status=exited)
# docker-compose up
# docker-compose up -d

# http://kvangundy.com/wp/set-up-neo4j-and-docker/
# https://blog.ouseful.info/2016/04/11/getting-started-with-the-neo4j-graph-database-linking-neo4j-and-jupyter-scipy-docker-containers-using-docker-compose/
# https://neo4j.com/docs/operations-manual/3.2/installation/docker/
# https://neo4j.com/developer/kb/explanation-of-error-websocket-connection-failure/


########
# neo4j:
#   image: neo4j:latest
#   ports:
#     - "7474:7474"
#     - "7473:7473"
#     - "7687:7687"
#   volumes:
#     - $HOME/Documents/hengchang/neo4j/data:/data
#     - $HOME/Documents/hengchang/neo4j/logs:/logs
#     - $HOME/Documents/hengchang/neo4j/import:/var/lib/neo4j/import
#     - $HOME/Documents/hengchang/neo4j/conf/:/conf/
# jupyterscipy:
#   image: sidazhou/scipy-notebook:latest
#   ports:
#     - "8888:8888"
#   links:
#     - neo4j:neo4j
#   volumes:
#     - .:/home/jovyan/work

